[program:cr_agent]
directory=/opt/app/cr_agent
command=/bin/bash -lc './scripts/start_service.sh prod'
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=30
priority=20
stdout_logfile=/opt/app/cr_agent/logs/supervisor.stdout.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stderr_logfile=/opt/app/cr_agent/logs/supervisor.stderr.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=10
environment=HOME="/root",USER="root",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin",CR_AGENT_DEPLOY_ENV="prod"
